account:
  name: "Playground"

users:
  - account: "Playground"
    email: "admin@sequinstream.com"
    password: "sequinpassword!"

api_tokens:
  - name: "loadtest-token"
    token: "sequin_loadtest_secret_token_12345"

databases:
  - name: "temporal-db"
    username: "temporal"
    password: "temporal_password"
    hostname: "temporal-postgresql"
    database: "temporal"
    port: 5432
    slot_name: "sequin_slot"
    publication_name: "sequin_pub"

sinks:
  - name: "temporal_tasks"
    database: "temporal-db"
    destination:
      type: "sequin_stream"
    source:
      include_tables:
        - "public.custom_task_queue"
